### ISSUE TITLE
ShellExecute failed

### ISSUE THREAD

**Issue by Ypot** [dmitrym0/org-hyperscheduler#17]
It seems more complicated to use than I thought. Do I need to start a webserver service on emacs?

- `M-x org-hyperscheduler-open`

- `browse-url-default-windows-browser: ShellExecute failed: El sistema no puede encontrar el archivo especificado.`

**Comment by dmitrym0** [comment]
How are you installing it? Based on #16, `(require 'org-hyperscheduler)` should be enough. `org-hyperscheduler-open` launches the browser with the bundled javascript file.

You can try `M-: (format "file://%s/calendar/index.html" org-hyperscheduler-root-dir)` and then stick the resulting URL into your favourite browser. Are you on windows?

**Comment by Ypot** [comment]
Hi
Yes, I am on Windows. I opened it manually from `\.emacs.d\elisp\org-hyperscheduler\calendar` and it worked, thanks :-)
